### ISSUE TITLE
MC should use the Unix exit code convention

### ISSUE THREAD

**Issue by taltman** [snayfach/MicrobeCensus#10]
MC reports "Error! No reads remaining after filtering!"

But the exit code is 0. Unix convention is to have a non-zero, non-negative exit code when there's an error.

This makes it harder to detect errors when running batches of MC runs via a script.

**Comment by snayfach** [comment]
I am using sys.exit("error message") whenever microbe_census exits prematurely.The exit code should be 1 in this case, and 0 when run to completion (https://docs.python.org/2/library/sys.html). Please make sure you are correctly detecting the exit code.

$ run_microbe_census.py -l 500 metagenome.fa.gz test.out
	Error! No reads remaining after filtering!
$ echo $?
1
