### ISSUE TITLE
temp files when program exits of error

### ISSUE THREAD

**Issue by jenmobberley** [snayfach/MicrobeCensus#11]
I have noticed that when MicrobeCensus errors out or execution is halted that the temp files created by the processes remain. You might want to consider altering the code to remove these files if the program exits prematurely.

**Comment by snayfach** [comment]
I've fixed this. You can find the changes reflected in release v1.0.6 on GitHub. These changes are not reflected yet in PyPI. Please let me know if you still have issues with this or have any other suggestions. Thanks for using MicrobeCensus!
