### ISSUE TITLE
installation on a cluster

### ISSUE THREAD

**Issue by Thomieh73** [snayfach/MicrobeCensus#12]
Hi,
I am trying to install MicrobeCensus on the abel computing cluster here in Oslo, Norway. The cluster runs on linux  64 bit Centos 6

Since I lack sufficient permissions, I followed your alternative installation suggestion.
I can load python2 (v2.7.10) since that has the biopython and numpy packages.

I have tested if I can import numpy and Bio.SeqIO on the python commandline.
I can. 
These packages are installed in the folder:

> /cluster/software/VERSIONS/python_packages-2.7_3/cluster/software/VERSIONS/python2-2.7.9/lib/python2.7/site-packages/

This folder is found in my $PYTHONPATH after loading python2.

Next I added microbecensus to the $PYTHONPATH
and I added the scripts to the $PATH.

When I then call: run_microbe_census.py -h
I get: 

> Could not import module 'numpy'

So I believe I have followed the correct way of setting this up, so I am surprised numpy is not found.

Do you have any idea on how I can solve this?

**Comment by Thomieh73** [comment]
Hi,
I actually overcame the installation issue on our cluster

I Installed MicrobeCensus using pip on my area on the computing cluster using the command:

pip install --user MicrobeCensus

after that I add the line to my .bash_profile file to point to the file run_microbe_census.py

export PATH=$PATH:/usit/abel/u1/thhaverk/.local/bin

Now I can run the program easily.

So in the instructions add the --user flag for pip. That makes it easier if you are not a superuser.
Thomas


ps. this tool runs well on my macbook.

**Comment by snayfach** [comment]
I've added that to the README on GitHub. Let me know if you have any other comments, questions, or suggestions. Thanks for using MicrobeCensus!
