### ISSUE TITLE
training.py: Unused test set?

### ISSUE THREAD

**Issue by psaxcode** [snayfach/MicrobeCensus#14]
Hi Stephen,
I just came across the  line for evaluation which reads:
error += test_error(train_genomes, train_rates, prop_constant, genome2size)
Does it mean to use  train_genomes, train_rates as the parameters?
Thanks

**Comment by snayfach** [comment]
Sorry, but I'm not exactly sure what you are asking. Could you try rephrasing the question?

**Comment by psaxcode** [comment]
Sorry for the confusion. I am talking about line 85 in the file https://github.com/snayfach/MicrobeCensus/blob/master/training/training.py, which is a statement in the function "xvalidation". I am just curious that the test set does not seem to be used here.

**Comment by snayfach** [comment]
Ah, I see what you mean now. I fixed the issue and the line now reads:
`error += test_error(test_genomes, test_rates, prop_constant, genome2size)`

The reported performance of MicrobeCensus in the paper is not affected by this bug.

Thanks,
Stephen
