### ISSUE TITLE
could not convert string to float: FIRM56_P641593085

### ISSUE THREAD

**Issue by chengdai** [snayfach/MicrobeCensus#18]
Hello,

I was running MicrobeCensus on my pair end reads and it threw the error:

could not convert string to float: FIRM56_P641593085
Traceback (most recent call last):
  File "/home/USR/miniconda2/bin/run_microbe_census.py", line 62, in <module>
    est_ags, args = microbe_census.run_pipeline(args)
TypeError: 'NoneType' object is not iterable

Is there any way of fixing this? Thanks!

**Comment by snayfach** [comment]
Could you send me the a sample of reads from the FASTQ files that are causing the issue?

**Comment by carden24** [comment]
I am having the same problem, do you have an update on this issue?

**Comment by snayfach** [comment]
Did you install the program from github or using pip? The github version is
more up to date. If installing from github, which version? If you send me a
sample of the data that is causing the issue I can investigate further

**Comment by carden24** [comment]
I did not notice that I had installed the pip version too (1.0.7). I uninstalled it, remove an older version, recloned the github repo and now seems to be working. On a completely unrelated question, I have unpaired and paired reads and I have been passing the three files (separated by commas). Do you think this could bias the results?. my unpaired reads are a mix of extended read, and orphan paired reads.  Thanks for the quick reply.
