### ISSUE TITLE
How the performance would be for metatranscriptomes?

### ISSUE THREAD

**Issue by SilentGene** [snayfach/MicrobeCensus#24]
Hi Stephen,

This is an awesome program that helped me a lot when to normalize the gene abundance across different samples. I just wonder can this software be used for metatranscriptomic data?

Cheers,
Heyu

**Comment by snayfach** [comment]
If you are mapping reads to a gene family database (e.g. KEGG), you could divide by the average abundance of the 30 universal genes (listed in manuscript table), which should be constitutively expressed.

**Comment by SilentGene** [comment]
Thanks for your suggestion, Stephen! I'll try that.
