### ISSUE TITLE
making sense of results...

### ISSUE THREAD

**Issue by jzrapp** [snayfach/MicrobeCensus#25]
Hi, thanks for this tool! Very easy to use and great documentation. Still, I'm struggeling with the output of my run. I'm working on a set of environmental samples that I would like to use for comparative analysis. However, the two types of sample sets differ in the contribution of eukaryotes (mainly diatoms), as well as viruses. As far as I understood from your paper, AGS may not be very reliable then, but RPKG may still be meaningful? I don't have a lot of examples to compare to, but I get the feeling that my estimates are very high, e.g.
Sample with very low expected contribution by eukaryotes: 
Parameters
metagenome:	CBmetaG_2.fastq.gz
reads_sampled:	2000000
trimmed_length:	150
min_quality:	-5
mean_quality:	-5
filter_dups:	False
max_unknown:	100

Results
average_genome_size:	18141036.055869997
total_bases:	46309620851
genome_equivalents:	2552.7550195246613

And sample with very large expected contribution by eukaryotes: 
Parameters
metagenome:	SBmetaG_2.fastq.gz
reads_sampled:	2000000
trimmed_length:	150
min_quality:	-5
mean_quality:	-5
filter_dups:	False
max_unknown:	100

Results
average_genome_size:	10211877.522966972
total_bases:	78896001286
genome_equivalents:	7725.905555423999

My gene prediction/counts were done on assembled reads, however as input for MicrobeCensus, I'm using the unassembled reads that were used as assembly input..
Am I doing this right? 

Thanks for your help!

**Comment by snayfach** [comment]
Yes you are doing everything right! Your AGS estimates are quite high, which as you mention, may be do to high levels of eukaryotes or viruses. 

Regardless, you can use the number of genome equivalents for normalization if you plan to perform comparative analyses between your samples.

Thanks,
Stephen

**Comment by jzrapp** [comment]
Thanks for your quick answer! Do you know of any other paper that reports the output from MicrobeCensus runs? I'd be curious to compare, but couldn't find any.

**Comment by snayfach** [comment]
Yes, there are decent number. You can look through [these](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=9409547349425432651,8933365353779665902) papers.
