### ISSUE TITLE
"Could not import module 'numpy'"

### ISSUE THREAD

**Issue by smurdock-UVic** [snayfach/MicrobeCensus#29]
Hi there,

Just trying out MicrobeCensus but I cannot get it to work. For both the test and run_microbe_census.py I get:
    Could not import module 'numpy'

I did the install using setup.py and have updated my numpy but I still get this error. Thoughts?

-Sheryl

**Comment by sapuizait** [comment]
same problem here - is there no solution for this?

**Comment by snayfach** [comment]
Not sure what's wrong, but my guess is that your PYTHONPATH needs to be updated. I just installed and ran using conda which worked fine. Can you try using conda or pip?

**Comment by sapuizait** [comment]
YES, it is working! The bioconda install solved the problem! Thanks for your quick response.
