### ISSUE TITLE
Could not import module 'pkg_resources'

### ISSUE THREAD

**Issue by tallnutt** [snayfach/MicrobeCensus#3]
Following the install instructions, get this error:
Could not import module 'pkg_resources'

Linux version 3.10-3-amd64 (debian-kernel@lists.debian.org) (gcc version 4.7.2 (Debian 4.7.2-5) ) #1 SMP Debian 3.10.11-1 (2013-09-10)

Python 2.7.3

**Comment by snayfach** [comment]
I think setuptools might be a missing dependency. What happens when you try
to import setuptools? Try typing: 'import setuptools' and 'import
pkg_resources' without the quotes into your python interpreter and let me
know the error you get.

Thanks,
Stephen

**Comment by snayfach** [comment]
I've removed the dependency on pkg_resources. Try downloading the latest release and trying again.
